/**
 * Export Engine — CSV + PDF report generation
 *
 * Supported formats:
 *   - CSV: full opportunity data with all scores
 *   - PDF: AI-generated summary (MiniMax) + key metrics table (via HTML string for browser printing)
 *   - Clipboard: copy-friendly text summary
 *
 * NOTE: PDF generation returns an HTML string that can be
 * printed via window.print() in the browser, or converted
 * via a headless PDF library server-side.
 */

import type { ActionType, EffortLevel } from './action-router';

export interface ExportOpportunity {
  query: string;
  page: string;
  position: number;
  ctr: number;
  impressions: number;
  clicks: number;
  estimatedGain: number;
  opportunityScore: number;
  actionType: ActionType;
  effort: EffortLevel;
  priority: number;
  status: 'open' | 'in_progress' | 'resolved' | 'dismissed';
}

export interface ExportOptions {
  format: 'csv' | 'pdf' | 'clipboard';
  siteUrl?: string;
  dateRange?: string;
  healthScore?: number;
  aiSummary?: string;
  includeResolved?: boolean;
}

// ─── CSV Export ───────────────────────────────────────────────────────────────

function escapeCSV(value: string | number | undefined): string {
  if (value === undefined || value === null) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function generateCSV(
  opportunities: ExportOpportunity[],
  options: ExportOptions,
): string {
  const rows = options.includeResolved
    ? opportunities
    : opportunities.filter(o => o.status !== 'resolved' && o.status !== 'dismissed');

  const headers = [
    'Query', 'Page', 'Position', 'CTR (%)', 'Impressions', 'Clicks',
    'Est. Monthly Gain (clicks)', 'Opportunity Score', 'Action Type',
    'Effort', 'Priority', 'Status',
  ];

  const lines = [
    `# SEOMaster Export — ${options.siteUrl ?? 'Site'} — ${options.dateRange ?? new Date().toLocaleDateString()}`,
    `# Health Score: ${options.healthScore ?? 'N/A'}/100`,
    '',
    headers.map(escapeCSV).join(','),
    ...rows.map(o => [
      escapeCSV(o.query),
      escapeCSV(o.page),
      escapeCSV(o.position.toFixed(1)),
      escapeCSV(o.ctr.toFixed(2)),
      escapeCSV(o.impressions),
      escapeCSV(o.clicks),
      escapeCSV(o.estimatedGain),
      escapeCSV(o.opportunityScore),
      escapeCSV(o.actionType),
      escapeCSV(o.effort),
      escapeCSV(o.priority),
      escapeCSV(o.status),
    ].join(',')),
  ];

  return lines.join('\n');
}

// ─── PDF (HTML) Export ────────────────────────────────────────────────────────

export function generatePDFHTML(
  opportunities: ExportOpportunity[],
  options: ExportOptions,
): string {
  const openOps = opportunities.filter(o => o.status === 'open' || o.status === 'in_progress');
  const totalGain = openOps.reduce((s, o) => s + o.estimatedGain, 0);
  const resolvedCount = opportunities.filter(o => o.status === 'resolved').length;

  const topOps = openOps.slice(0, 10);

  const tableRows = topOps.map((o, i) => `
    <tr style="background:${i % 2 === 0 ? '#f9f9f9' : '#fff'}">
      <td>${i + 1}</td>
      <td style="max-width:200px;overflow:hidden;text-overflow:ellipsis">${o.query}</td>
      <td>${o.position.toFixed(1)}</td>
      <td>${o.ctr.toFixed(2)}%</td>
      <td>${o.impressions.toLocaleString()}</td>
      <td><strong>+${o.estimatedGain}</strong></td>
      <td>${o.opportunityScore}/100</td>
      <td>${o.actionType.replace(/_/g, ' ')}</td>
      <td>${o.effort}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>SEOMaster Report — ${options.siteUrl ?? 'Site'}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; margin: 40px; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  .meta { color: #666; font-size: 13px; margin-bottom: 32px; }
  .kpi-row { display: flex; gap: 24px; margin-bottom: 32px; }
  .kpi { background: #f5f5f5; padding: 16px 24px; border-radius: 8px; min-width: 120px; }
  .kpi-value { font-size: 28px; font-weight: 700; }
  .kpi-label { font-size: 12px; color: #888; margin-top: 4px; }
  .summary { background: #f0f4ff; border-left: 4px solid #4f8ef7; padding: 16px 20px; border-radius: 4px; margin-bottom: 32px; font-size: 14px; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; background: #1a1a2e; color: #fff; font-size: 11px; letter-spacing: 0.04em; }
  td { padding: 9px 12px; border-bottom: 1px solid #eee; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<h1>SEOMaster SEO Report</h1>
<div class="meta">${options.siteUrl ?? 'Site'} · ${options.dateRange ?? new Date().toLocaleDateString()} · Generated by SEOMaster</div>

<div class="kpi-row">
  <div class="kpi"><div class="kpi-value">${options.healthScore ?? '—'}</div><div class="kpi-label">Health Score</div></div>
  <div class="kpi"><div class="kpi-value">${openOps.length}</div><div class="kpi-label">Open Opportunities</div></div>
  <div class="kpi"><div class="kpi-value">+${totalGain.toLocaleString()}</div><div class="kpi-label">Est. Monthly Gain</div></div>
  <div class="kpi"><div class="kpi-value">${resolvedCount}</div><div class="kpi-label">Issues Resolved</div></div>
</div>

${options.aiSummary ? `<div class="summary"><strong>AI Executive Summary:</strong><br>${options.aiSummary}</div>` : ''}

<h2 style="margin-bottom:16px">Top 10 Opportunities</h2>
<table>
  <thead>
    <tr>
      <th>#</th><th>Query</th><th>Position</th><th>CTR</th><th>Impressions</th>
      <th>Est. Gain</th><th>Score</th><th>Action</th><th>Effort</th>
    </tr>
  </thead>
  <tbody>${tableRows}</tbody>
</table>

<p style="margin-top:32px;font-size:11px;color:#999">Generated by SEOMaster Premium · ${new Date().toISOString()}</p>
</body>
</html>`;
}

// ─── Clipboard Text ───────────────────────────────────────────────────────────

export function generateClipboardText(
  opportunities: ExportOpportunity[],
  options: ExportOptions,
): string {
  const topOps = opportunities.filter(o => o.status === 'open').slice(0, 5);
  const lines = [
    `SEOMaster Report — ${options.siteUrl ?? 'Site'}`,
    `Health Score: ${options.healthScore ?? 'N/A'}/100`,
    '',
    'Top 5 Opportunities:',
    ...topOps.map((o, i) =>
      `${i + 1}. "${o.query}" (pos ${o.position.toFixed(1)}) — ${o.actionType.replace(/_/g, ' ')} — est. +${o.estimatedGain} clicks/mo`,
    ),
  ];
  return lines.join('\n');
}
